---
# file: site.yml
# configures all nodes instances
# This playbook has one play for installing software in all kubernetes cluster nodes

# This play installs software in all kubernetes cluster nodes
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      pkg: "{{ packages }}"
      state: present
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: no

  # Installing kubelet, kubeadm and kubectl
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
  
  - name: Add Google apt signing key
    apt_key:
      url: hkp://keyserver.ubuntu.com:80
      id: 6A030B21BA07F4FB
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list
      update_cache: no

  - name: retry if needed using command apt-get update
    command: apt-get update

  # Install Docker and its dependent components
  - name: Install docker and its dependecies
    apt: 
      pkg: "{{ packages }}"
      state: present
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
  
  - name: Start docker
    service: name=docker state=started

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  # Kubelet will not start if the system has swap enabled, so we are disabling swap
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
      cache_valid_time: 3600
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
    ignore_errors: yes
    
  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_host }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted